---

- name: install vim packages
  become: yes
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - vim-nox

- name: install vim-plug
  command: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  args:
    creates: ~/.vim/autoload/plug.vim
